// src/lib/components/bridge/OperationProxy.svelte
<script lang="ts">
  import { debounce } from 'lodash-es'
  import FaAngleDown from 'svelte-icons/fa/FaAngleDown.svelte'
  import { getTemplate, proxyOperation } from '$lib/api/bridge.api'
  import type { JsonContent } from '$lib/components/JsonView.svelte'
  import JsonView from '$lib/components/JsonView.svelte'
  import LazyElement from '$lib/components/LazyElement.svelte'
  import type { OperationId, ProxyRequest } from '$lib/data/service.model'
  import {
    copyToClipboard,
    fromBase64,
    prettyJson,
    toBase64,
    tryParseJson,
  } from '$lib/utils/string.utils'
  import { urlWithQueryParams } from '$lib/utils/url.utils'
  import { page } from '$app/stores'
  import * as storage from '$lib/data/template.storage'

  export let operationId: OperationId
  let copiedUrl = false

  let endpoint: string
  let bodyContent: JsonContent | null
  let response: Promise<object> | null = null

  $: operationId, fetchRequestTemplate()
  $: body = tryParseJson(bodyContent?.text)
  $: endpoint, body, persistProxyRequest()

  let persistProxyRequest = debounce(() => {
    body &&
      storage.persistProxyRequest(operationId, {
        endpoint,
        body,
      })
  }, 300)

  function onProxyOperation() {
    if (endpoint && body) {
      response = proxyOperation(operationId, endpoint, body)
    }
  }

  function copyPersistentUrl() {
    copiedUrl = true
    const request: ProxyRequest = { endpoint, body: body || {} }
    const copyText = urlWithQueryParams({ form: toBase64(request) })
    copyToClipboard(copyText).then(() =>
      setTimeout(() => (copiedUrl = false), 300)
    )
  }

  function resetForm() {
    bodyContent = null
    fetchOriginalRequestTemplate()
  }

  function fetchRequestTemplate() {
    bodyContent = null
    const formParam = $page.url.searchParams.get('form')
    if (formParam) {
      const request: ProxyRequest = fromBase64(formParam)
      endpoint = request.endpoint
      updateBody(request.body)
    } else {
      const proxyRequest = storage.getProxyRequest(operationId)
      endpoint = proxyRequest.endpoint
      if (proxyRequest.body) {
        updateBody(proxyRequest.body)
      } else {
        fetchOriginalRequestTemplate()
      }
    }
  }

  function fetchOriginalRequestTemplate() {
    getTemplate(operationId).then(
      (val) => updateBody(val),
      (rej) => updateBody({ error: rej })
    )
  }

  function updateBody(json: object) {
    bodyContent = {
      text: prettyJson(json),
    }
  }
</script>

<form class="proxy-service" on:submit|preventDefault={onProxyOperation}>
  <div class="action-row">
    <input
      type="text"
      placeholder="Endpoint"
      class="input"
      class:is-danger={!endpoint}
      bind:value={endpoint}
    />
    <div class="split-button">
      <button type="submit" class="button is-info">Send</button>
      <div class="dropdown is-right is-hoverable">
        <div class="dropdown-trigger">
          <button type="button" class="button is-info">
            <span class="icon is-small">
              <FaAngleDown />
            </span>
          </button>
        </div>
        <div class="dropdown-menu" id="dropdown-menu2" role="menu">
          <div
            class="dropdown-content"
            class:has-background-success={copiedUrl}
          >
            <!-- svelte-ignore a11y-missing-attribute -->
            <a class="dropdown-item" on:click={copyPersistentUrl}>
              Copy persistent url
            </a>
          </div>
          <div class="dropdown-content">
            <!-- svelte-ignore a11y-missing-attribute -->
            <a class="dropdown-item" on:click={resetForm}> Reset body </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr />
  <div class="request-row">
    <JsonView bind:content={bodyContent} />
  </div>
  <hr />
  <div class="response-row">
    <LazyElement lazy={response} let:loaded={_resp}>
      <JsonView
        content={_resp && { text: prettyJson(_resp) }}
        readOnly={true}
      />
    </LazyElement>
  </div>
</form>

<style>
  form.proxy-service {
    height: 100%;
    display: flex;
    flex-direction: column;
  }

  .action-row {
    display: flex;
  }

  .action-row .split-button {
    margin-left: 10px;
    display: inline-flex;
  }

  .action-row .split-button button {
    border-color: #837ea9;
  }

  .action-row .split-button > button {
    border-top-right-radius: 0%;
    border-bottom-right-radius: 0%;
    border-right: 0px;
  }

  .action-row .split-button .dropdown button {
    border-top-left-radius: 0%;
    border-bottom-left-radius: 0%;
    width: 75%;
  }

  .request-row {
    height: 40vh;
  }

  .response-row {
    height: 30vh;
  }
</style>

// src/app/bridge/components/operation-proxy/operation-proxy.component.ts
import { Component, Input, SimpleChanges, OnInit, OnChanges } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { JsonEditorOptions } from 'ang-jsoneditor';
import { ClipboardService } from 'app/bridge/shared/clipboard.service';

import { OperationId, ProxyRequest } from 'app/bridge/shared/service.model';
import { ServicesService } from 'app/bridge/shared/services.service';
import { debounceTime } from 'rxjs/operators';

@Component({
  selector: 'app-operation-proxy',
  templateUrl: './operation-proxy.component.html',
  styleUrls: ['./operation-proxy.component.css']
})
export class OperationProxyComponent implements OnInit, OnChanges {

  @Input() operationId!: OperationId;

  form: FormGroup;
  editorOptions = new JsonEditorOptions();
  response?: string;
  loading = false;
  copiedUrl = false;

  constructor(
    private clipboard: ClipboardService,
    private servicesService: ServicesService
  ) {
    this.editorOptions.mode = 'code';
    this.editorOptions.mainMenuBar = false;

    this.form = new FormGroup({
      'endpoint': new FormControl('', [Validators.required]),
      'body': new FormControl('')
    });
  }

  ngOnInit() {
    this.form.valueChanges.pipe(
      debounceTime(1000)
    ).subscribe(
      (data: ProxyRequest) =>
        this.servicesService.persistProxyRequest(this.operationId, data)
    );
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.operationId && changes.operationId.currentValue) {
      this.clearForm();
      this.fillForm();
    }
  }

  fillForm() {
    this.servicesService.getProxyRequest(this.operationId)
      .subscribe(
        data => {
          this.f['endpoint'].setValue(data.endpoint);
          this.f['body'].setValue(data.body);
        },
        _ => this.onError()
      );
  }

  resetForm() {
    this.servicesService.getTemplate(this.operationId)
      .subscribe(
        template => this.f['body'].setValue(template),
        _ => this.onError()
      );
  }

  clearForm() {
    this.f['endpoint'].setValue('');
    this.f['body'].setValue('{}');
    this.response = '';
  }

  get f() {
    return this.form.controls;
  }

  proxy() {
    if (this.form.valid) {
      this.loading = true;
      this.response = '';
      const value = this.form.value as ProxyRequest;
      this.servicesService.proxy(this.operationId, value)
        .subscribe(
          data => this.response = JSON.stringify(data, null, 4),
          ex => this.response = JSON.stringify(ex.error, null, 4),
          () => this.loading = false
        );
    }
  }

  copyPersistentUrl() {
    const formParam = btoa(JSON.stringify(this.form.value));
    this.clipboard.copyText(window.location.href + '?form=' + formParam);
    this.copiedUrl = true;
    setTimeout(() => (this.copiedUrl = false), 300);
  }

  onError() {
    this.response = 'Something went wrong :(';
  }
}

<form class="proxy-service" [formGroup]="form" (ngSubmit)="proxy()">
  <div class="action-row">
    <input type="text" placeholder="Endpoint" class="input" [class.is-danger]="f.endpoint.invalid"
      formControlName="endpoint">
    <div class="split-button">
      <button type="submit" class="button is-info">Send</button>
      <div class="dropdown is-right is-hoverable">
        <div class="dropdown-trigger">
          <button type="button" class="button is-info">
            <span class="icon is-small">
              <fa-icon icon="angle-down"></fa-icon>
            </span>
          </button>
        </div>
        <div class="dropdown-menu" id="dropdown-menu2" role="menu">
          <div class="dropdown-content" [class.has-background-success]="this.copiedUrl">
            <a class="dropdown-item" (click)="copyPersistentUrl()">
              Copy persistent url
            </a>
          </div>
          <div class="dropdown-content">
            <a class="dropdown-item" (click)="resetForm()">
              Reset body
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr />
  <div class="request-row">
    <json-editor [options]="editorOptions" formControlName="body"></json-editor>
  </div>
  <hr />
  <div class="response-row">
    <div class="control" [class.is-loading]="loading">
      <textarea disabled *ngIf="response" value="{{response}}"></textarea>
    </div>
  </div>
</form>
